[package]
name = "piawg"
version = "0.1.0-dev"
authors = ["Fletcher Nichol <fnichol@nichol.ca>"]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/fnichol/piawg"
documentation = "https://github.com/fnichol/piawg"
homepage = "https://github.com/fnichol/piawg"
keywords = ["TODO(fnichol): fill in"]
categories = ["TODO(fnichol): fill in"]
description = """
TODO(fnichol): fill in
"""

[features]
default = ["application"]

# Required for building the CLI application. Should be disabled when depending
# on the crate as a library. For example, to use as a library in a Cargo.toml:
# `piawg = { version = "...", default-features = false }`
application = ["clap"]

[dependencies]
# A CLI-specific dependency
clap = { version = "3.0.0-beta.2", optional = true }

[dev-dependencies]
version-sync = "0.9.2"

[package.metadata.docs.rs]
no-default-features = true
